# Generated by Django 6.0.5 on 2026-06-29 10:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_today', models.DateField()),
                ('worker_count', models.IntegerField()),
                ('site_manager', models.CharField(max_length=200)),
                ('work_overview', models.TextField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('site_worked_on', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logs.site')),
            ],
        ),
    ]
