# Generated by Django 6.0.5 on 2026-06-29 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0002_dailylog'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_name', models.CharField(max_length=200)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(choices=[('bags', 'Bags'), ('kg', 'Kilgoram'), ('lt', 'Litres')], max_length=20)),
                ('daily_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logs.dailylog')),
            ],
        ),
    ]
