# Generated by Django 6.0.5 on 2026-07-02 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0003_materialentry'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailylog',
            options={'verbose_name_plural': 'Daily Log'},
        ),
        migrations.AlterModelOptions(
            name='materialentry',
            options={'verbose_name_plural': 'Material Entries'},
        ),
        migrations.AddField(
            model_name='site',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('on hold', 'On Hold'), ('completed', 'Completed')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='materialentry',
            name='unit',
            field=models.CharField(choices=[('bags', 'Bags'), ('kg', 'Kilgoram'), ('lt', 'Litres'), ('unit', 'Units')], max_length=20),
        ),
    ]
