# Generated by Django 6.0.5 on 2026-07-05 16:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0006_attendance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='workers',
            field=models.ManyToManyField(blank=True, related_name='assigned_sites', to=settings.AUTH_USER_MODEL),
        ),
    ]
