# Generated by Django 6.0.7 on 2026-07-10 18:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0007_site_workers'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialentry',
            name='unit',
            field=models.CharField(choices=[('bags', 'Bags'), ('kg', 'Kilogram'), ('lt', 'Litres'), ('unit', 'Units')], max_length=20),
        ),
        migrations.AddConstraint(
            model_name='attendance',
            constraint=models.UniqueConstraint(fields=('worker', 'worksite', 'attendance_date'), name='one_attendance_per_worker_site_day'),
        ),
    ]
