# Generated by Django 6.0.7 on 2026-07-11 01:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0009_attendance_marked_at_attendanceqrcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailylog',
            name='worker_count',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='materialentry',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
